### ISSUE TITLE
Dealing with padding trailing bytes in notifications received

### ISSUE THREAD

**Issue by realvarx** [atsign-foundation/at_pico_w#25]
### Is your feature request related to a problem? Please describe.

Receiving messages with some strings results in a set of repeated bytes at the end of the message (PKCS AES padding). The word `"test"` is one of those words:
```
alvaro@rs-2022:~/Desktop/update/at_pico_w/src$ micropython main.py
Welcome! What would you like to do?
        1) Change recipient atSign (presently alvaro)
        2) Connect to arrogantcheetah
        3) Send at atTalk message to alvaro
        4) Exit
> 2
Connecting to arrogantcheetah...
Connected
Welcome! What would you like to do?
        1) Change recipient atSign (presently alvaro)
        2) Connect to arrogantcheetah
        3) Send at atTalk message to alvaro
        4) Exit
> 3
To return to menu type: /exit

@alvaro: hello
@alvaro: testing
@alvaro: test












@alvaro: issue happened!
yes
```

This is currently handled with the function `remove_trailing`, which tries to remove the most usual trailing bytes which I have observed, but it doesn't guarantee that other different non-handled trailing bytes (see [these](https://www.ibm.com/docs/en/zos/2.4.0?topic=rules-pkcs-padding-method) docs) will eventually appear. 

### How to see it

1. Substitute this line of code:
https://github.com/atsign-foundation/at_pico_w/blob/849b3f6c4a0b38de6ec5ff884cdc14abce3e1d29/src/lib/atclient.py#L359
By the following:
```
decrypted_msg = decrypted_msg_b.decode('utf-8').rstrip("\v")
```
(So it is possible to visualize the issue)

3. Using the MicroPython client, connect to your secondary (option 2) and then start talking with your recipient (option 3). Don't send any message.
4. Open a different attalk client (you can use Dart one) and send the word `"test"` to the atSign which is listening in the MicroPython client.
5. See that many "spaces" have been introduced with the last message received (`"test"` word message). Those are not spaces or line jumps, they are actually other kind of characters which have been described below.

Adding the following lines to the `attalk_recv` method:
```
print("aesKey: " + ubinascii.b2a_base64(self.sharedkeyrecp).rstrip().decode() + ", iv: " + ubinascii.b2a_base64(iv).rstrip().decode())
print(notifications[-1]['value'].rstrip().encode())
```
We can obtain the necessary data needed to decrypt the message. 

- Now we can use [CyberChef](https://gchq.github.io/CyberChef/#recipe=From_Base64('A-Za-z0-9%2B/%3D',true,false)AES_Decrypt(%7B'option':'Base64','string':'recipientsharedkey%20(b64)'%7D,%7B'option':'Base64','string':'ivNonce%20(b64)'%7D,'CTR','Raw','Raw',%7B'option':'Hex','string':''%7D,%7B'option':'Hex','string':''%7D)&input=Tk9USUZJQ0FUSU9OIFZBTFVFIEZJRUxEIAoodGhlIGVuY3J5cHRlZCBtZXNzYWdlIGluIGI2NCk) to look more closely to the decryption process:
![image](https://github.com/atsign-foundation/at_pico_w/assets/71457057/f43e74a0-aa25-42c8-bb4d-918c7524b9d9)

- Changing the `Output` from `Hex` to `Raw` we can see which is the encoded value:
![image](https://github.com/atsign-foundation/at_pico_w/assets/71457057/f30d8395-92c3-4690-b8c0-de16755f7d31)

- `FF` stands for `Form Field`, which representation in bytes is `0c`. 
- This same issue has also been observed when sending other different messages, resulting in `0a` (`LF` `Line Feed`) or `0b` (`VT` `Vertical Tab`) among other characters.

### Expected behavior

The console should print "test" (or any other message which repplicates the issue) with no extra trailing characters.

### Describe the solution you'd like
Implement PKCS AES unpad method propperly

**Comment by JeremyTubongbanua** [comment]
@realvarx Maybe these could be of any help?

https://github.com/atsign-foundation/at_c/blob/d83f930be773246e2aeab4cf1ad3f953efa7184e/src/at_chops/aes_ctr.c#L140

https://www.ibm.com/docs/en/zos/2.4.0?topic=rules-pkcs-padding-method

**Comment by realvarx** [comment]
> @realvarx Maybe these could be of any help?
> 
> https://github.com/atsign-foundation/at_c/blob/d83f930be773246e2aeab4cf1ad3f953efa7184e/src/at_chops/aes_ctr.c#L140
> 
> https://www.ibm.com/docs/en/zos/2.4.0?topic=rules-pkcs-padding-method

Ohhh how could I not take notice of that! I even looked for an unpad method, but I thought padding was all zeroes and one byte representing the size of it, for some reason :grimacing:

Thx @JeremyTubongbanua ! :smile:

**Comment by realvarx** [comment]
Fixed by https://github.com/atsign-foundation/at_pico_w/commit/45fcd8829be149a21134be6515dab93c62b91f9e
