### ISSUE TITLE
Unexpected Errors

### ISSUE THREAD

**Issue by Intiserahmed** [atsign-foundation/at_pico_w#4]
**Describe the Error**
<img width="413" alt="Screenshot 2022-09-05 at 1 28 02 PM" src="https://user-images.githubusercontent.com/57252940/188366934-1176d23b-030d-4afe-bf16-793252e1da14.png">

I have plaed value at setting.json but when I try to run the main.py wifi gets connected then these errors pops up.
Way arround?

**To Reproduce**
1. First I '...'
2. Then I '...'
3. And then '...'
4. 

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS14.1]
 - Version [e.g. 59]

**Were you using an atApplication when the bug was found?**
  - [e.g. Buzz, Atmosphere]

**Additional context**

**Comment by realvarx** [comment]
Sometimes that bug happened with the previous version (relaunching the `main.py` file again would solve it most of the times) Should be working fine with the last update
